Create animals table
Sami-Ullah-Tufail/postgresql-vetclinic pull request #1
Opened 2023-11-03 20:26 UTC by Sami-Ullah-Tufail

### In this Milestone I checked the following tasks:

- [ ] Create a database named vet_clinic.
- [ ]  Create a table named animals.
- [ ]  Insert the required data.
- [ ]  Write queries for the following quests:
                  

- [ ] ![data 8](https://github.com/Sami-Ullah-Tufail/postgresql-vetclinic/assets/114190100/ca3146d3-c423-42c7-9cb9-711b82145083)
- [ ] ![data 7](https://github.com/Sami-Ullah-Tufail/postgresql-vetclinic/assets/114190100/1a1a425b-7c1c-4fa6-ba90-68956d2b7794)
- [ ] ![data 6](https://github.com/Sami-Ullah-Tufail/postgresql-vetclinic/assets/114190100/8f74a380-991d-4c9a-829a-7b35dd38b429)
- [ ] ![data 5](https://github.com/Sami-Ullah-Tufail/postgresql-vetclinic/assets/114190100/10208eb9-9c5c-4088-ad14-d4cf965ba00b)
- [ ] ![data 4](https://github.com/Sami-Ullah-Tufail/postgresql-vetclinic/assets/114190100/ebf8d105-32a1-496b-bf9f-c7232de79462)
- [ ] ![data 3](https://github.com/Sami-Ullah-Tufail/postgresql-vetclinic/assets/114190100/4132f88d-f789-49ab-bbcb-beaa6305211e)
- [ ] ![data 2](https://github.com/Sami-Ullah-Tufail/postgresql-vetclinic/assets/114190100/b3b6f5e6-5325-48e8-87c2-d52d57476595)
- [ ] ![data 1](https://github.com/Sami-Ullah-Tufail/postgresql-vetclinic/assets/114190100/97005538-bdac-4794-be54-db1e415bf9ef)

2023-11-03 21:03 UTC, zeff96 requested changes
### Status: CHANGES REQUIRED ♻️
Hi @Sami-Ullah-Tufail , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/200w.webp?cid=ecf05e474zgjzn6tl2dpm5095td5cxjr6dsk9egrm20w4iw4&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
:heavy_check_mark: Correct GitFlow
:heavy_check_mark: Descriptive pull request


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-03 21:03 UTC, zeff96 commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [x] Hello, Kindly have a look at the license link and fix it as it is currently broken

```sh
This project is [MIT](./License) licensed. #should work and fix the issue of broken link
```

2023-11-04 11:02 UTC, rloterh commented on README.md
>  This project is [MIT](./LICENSE) licensed.
This issue is well resolved! ✔️

2023-11-04 11:04 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Sami,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Good job on implementing recommended changes!

Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-04 17:44 UTC, merged